### ISSUE TITLE
Kimler yardım etmek istiyor?

### ISSUE THREAD

**Issue by sumnulu** [CoronaBuster/CoronaBuster#1]
Comment olarak hangi konuda yardım etmek istediğinizi yazabilirsiniz.
Yada yardım edecek tanıdığınız birisi varsa ilgili kişiyi yönlendirebilirsiniz.

**Comment by erhanyasar** [comment]
Selam,
Ne zaman başlayacağı ve günde kaç saat çalışma gibi bir ayrıntı verebiliyorsan Lead Frontend olarak destek olabilirim belki.

**Comment by sumnulu** [comment]
@erhanyasar biz baslamistik ama yeterince ilgilenen kisi olmadi. Bakanlik benzer bir yazilim yapiyo bizim ugrasmamiza gerek yok diye dusunuyorum.
